//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BevasarloLista.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BevasarloLista.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hozzáad.
        /// </summary>
        public static string addButton {
            get {
                return ResourceManager.GetString("addButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hozzáadás.
        /// </summary>
        public static string addTitle {
            get {
                return ResourceManager.GetString("addTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mennyiség.
        /// </summary>
        public static string itemAmountEntry {
            get {
                return ResourceManager.GetString("itemAmountEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válassz egy típust.
        /// </summary>
        public static string itemAmountTypePicker {
            get {
                return ResourceManager.GetString("itemAmountTypePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név.
        /// </summary>
        public static string itemNameEntry {
            get {
                return ResourceManager.GetString("itemNameEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés Facebookkal.
        /// </summary>
        public static string loginFBButton {
            get {
                return ResourceManager.GetString("loginFBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés Googleval.
        /// </summary>
        public static string loginGoogleButton {
            get {
                return ResourceManager.GetString("loginGoogleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        public static string loginTitle {
            get {
                return ResourceManager.GetString("loginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BevásárlóLista.
        /// </summary>
        public static string mainTitle {
            get {
                return ResourceManager.GetString("mainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módosítás.
        /// </summary>
        public static string modifyTitle {
            get {
                return ResourceManager.GetString("modifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adj meg egy becenevet..
        /// </summary>
        public static string nicknameLabel {
            get {
                return ResourceManager.GetString("nicknameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új Bevásárló elem.
        /// </summary>
        public static string pushNotifyTitle {
            get {
                return ResourceManager.GetString("pushNotifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        public static string saveButton {
            get {
                return ResourceManager.GetString("saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        public static string signOutButton {
            get {
                return ResourceManager.GetString("signOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        public static string userinfoSave {
            get {
                return ResourceManager.GetString("userinfoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becenév.
        /// </summary>
        public static string userinfoTitle {
            get {
                return ResourceManager.GetString("userinfoTitle", resourceCulture);
            }
        }
    }
}
